name: Tests

on:
  workflow_dispatch:
  push:
    paths: ['**/*.js'] # only run workflow when source files changed
  pull_request:
    paths: ['**/*.js']
  schedule:
    # run tests monthly to prevent Algolia test index from being suspended due to inactivity
    - cron: '0 0 1 * *' # at 00:00 UTC on 1st day of every month (https://crontab.guru)

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
